apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://{{ .Values.database.username }}@{{ .Values.database.host }}/{{ .Values.database.name }}
        resources:
{{ toYaml .Values.resources | indent 10 }}