apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  type: ClusterIP  # Can be changed to NodePort or LoadBalancer as needed
  ports:
    - port: 80        # Service port
      targetPort: 5000  # Container port
      protocol: TCP
  selector:
    app: python-app   # Matches the deployment's label selector